### PR TITLE
Organize idl

### PR DESCRIPTION
**Pull request by pearsonk**
Use an XSLT to organize the IDL files without changing the semantics of any of the resulting stubs. This improves human-readability, especially if documentation auto-generators do not alphabetize or organize for themselves.

### CODE REVIEW

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt64/builds/6657

**Comment by pearsonk** [comment]
Hold on merging this, I will look into a graceful newline mechanism for the XSLT to add empty newline text nodes to break up the text a bit.

**Comment by pearsonk** [comment]
Unfortunately, adding the requested change from @jean-edouard isn't straight-forward. As soon as I added a single <xsl:text> it causes my xslt processors to ignore the top-level indent="yes" formatter, which would cause the XSLT to be responsible for explicitly performing output formatting, which is a lot of messy work and probably not worth it.

**Comment by jean-edouard** [comment]
No problem, thanks for trying :)
Will merge next week.

**Pull request merged**
