### PR TITLE
Vusb policy

### PR DESCRIPTION
**Pull request by pearsonk**
Data type cleanup in rpc-gen and interfaces for USB policy management.

Depends on https://github.com/OpenXT/vusb-daemon/pull/25

### CODE REVIEW

**Comment by pearsonk** [comment]
Pushed rebased commit with spelling fix.

**Comment by jandryuk** [comment]
I think these changes are generally good, but I have some questions.

What is a rule "page"?

Is there a specific reason for the three policy_set_rule variants? Naively, I would assume just one with lots of optional parameters. But I don't know dbus enough to know if that is feasible.

And I'll comment on it here since it's a more general thing. In the vusb code, you switched the rule number type to uint16.  I agree with unsigned, but I wonder if there is any reason to restrict to 16bits. I could be wrong, but I though the code would handle 32bit numbers and 16bit was just a convention. Maybe 32bit is not practical, but maybe we shouldn't restrict ourselves?

**Comment by pearsonk** [comment]
A page of rules is just a subset of the total set of rules, to simplify UI
development as well as reduce the size of DBus queries for large policies.

The reason for the variants is to provide wrappers to more complex
interfaces. If an implementation only cares about VID/PID/Serial matching,
they won't have to worry about DBus structs/dicts. It also aids the use of
'xec -s' and dbus-send, which do not support creating of a DBus struct
parameter, so the alternatives can be used for the sake of simplicity.

The reason for making it limited to 65535 rules is to better avoid pushing
the upper limit of DBus message size for a fully-populated rule set query
(plus all the cruft that wraps DBus). Aside from that, it was fairly
arbitrary selection to match the positive half of a signed 32-bit integer.

**Comment by jandryuk** [comment]
Sorry, I lost track of this.  Do you have a work-in-progress or plan for a future consumer of these interfaces?  I guess it doesn't matter since we don't need to maintain backwards compatibility, but typically you want to ensure new interfaces meet the user's needs.  They do seem reasonable and a step forward.

One thing with the policy_get_rules_page interface.  A caller doesn't know if the rules have changed under its feet between subsequent calls - i.e. missing an added rule or getting a duplicate.  I'm not an expert on interface design, so other solutions are welcome, but one idea is to return a generation number with each policy_get_rules_page call.  Whenever vusb-daemon modifies its rules, the generation is incremented.  A just needs to ensure the generation id remains the same throughout its processing.  If it changes, the caller needs to start again.

**Comment by pearsonk** [comment]
The main plan is the ability to deploy device policies via the syncvm along with VMs. The generic (usb-enabled) policy and default rules aren't sufficient for use cases such as limiting a particular VM to a specific smart card reader, and hard-coding or manually entering rules on each workstation terminal doesn't scale well.

Regarding the pagination, from what I have seen common implementations don't usually track or maintain response versioning, which suffers from the issues you mentioned (see GitHub APIs as an example). It is largely intended to be a convenience function to retrieve smaller data sets instead of the complete policy in a single call. If it is believed that the pagination will lead to confusion or better to be deferred to a caller's implementation, it can be removed. It would be a fairly simple change.

**Comment by pearsonk** [comment]
Updated and rebased to remove the policy_get_rules_page

**Comment by jandryuk** [comment]
Nice use case with the syncvm.

If you find you need the pagination interface, it can always be added.

The Haskell change is unfortunate, but like you wrote, we shouldn't be using it for new code.

**Comment by eric-ch** [comment]
Will merge soon.

**Pull request merged**
